# -*- coding: utf-8 -*-
"""final_data_and_label.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dJrk_x7LiqeaW09hxsH8-a7VbZONowdD
"""

from google.colab import drive
drive.mount('/content/drive')
n = 6

"""### **This script provides the final data sheet with labels**"""

import pandas as pd
sync_csv_path = f'/content/drive/MyDrive/data/organization/picking/pick_mustard/Experiment{n}/synchronised_data.csv'
df_s = pd.read_csv(sync_csv_path)
# df_s.columns.to_list()
# range(1, len(df_s))

"""## Change the column name"""

# cartesian pose
df_s.rename(columns={"processed_data_cartesian_pose_bicep0": "robot_arm_bicep_pos_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_bicep1": "robot_arm_bicep_pos_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_bicep2": "robot_arm_bicep_pos_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_bicep3": "robot_arm_bicep_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_bicep4": "robot_arm_bicep_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_bicep5": "robot_arm_bicep_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_bicep6": "robot_arm_bicep_quat_w"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_pose_end_effector0": "robot_arm_end_effector_pos_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_end_effector1": "robot_arm_end_effector_pos_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_end_effector2": "robot_arm_end_effector_pos_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_end_effector3": "robot_arm_end_effector_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_end_effector4": "robot_arm_end_effector_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_end_effector5": "robot_arm_end_effector_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_end_effector6": "robot_arm_end_effector_quat_w"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_pose_forearm0": "robot_arm_forearm_pos_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_forearm1": "robot_arm_forearm_pos_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_forearm2": "robot_arm_forearm_pos_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_forearm3": "robot_arm_forearm_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_forearm4": "robot_arm_forearm_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_forearm5": "robot_arm_forearm_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_forearm6": "robot_arm_forearm_quat_w"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_pose_shoulder0": "robot_arm_shoulder_pos_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_shoulder1": "robot_arm_shoulder_pos_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_shoulder2": "robot_arm_shoulder_pos_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_shoulder3": "robot_arm_shoulder_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_shoulder4": "robot_arm_shoulder_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_shoulder5": "robot_arm_shoulder_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_shoulder6": "robot_arm_shoulder_quat_w"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_10": "robot_arm_spherical_wrist_1_pos_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_11": "robot_arm_spherical_wrist_1_pos_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_12": "robot_arm_spherical_wrist_1_pos_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_13": "robot_arm_spherical_wrist_1_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_14": "robot_arm_spherical_wrist_1_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_15": "robot_arm_spherical_wrist_1_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_16": "robot_arm_spherical_wrist_1_quat_w"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_20": "robot_arm_spherical_wrist_2_pos_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_21": "robot_arm_spherical_wrist_2_pos_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_22": "robot_arm_spherical_wrist_2_pos_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_23": "robot_arm_spherical_wrist_2_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_24": "robot_arm_spherical_wrist_2_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_25": "robot_arm_spherical_wrist_2_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_spherical_wrist_26": "robot_arm_spherical_wrist_2_quat_w"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_pose_wheelchair0": "wheelchair_pos_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_wheelchair1": "wheelchair_pos_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_wheelchair2": "wheelchair_pos_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_wheelchair3": "wheelchair_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_wheelchair4": "wheelchair_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_wheelchair5": "wheelchair_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_pose_wheelchair6": "wheelchair_quat_w"}, inplace=True)

# cartesian v
df_s.rename(columns={"processed_data_cartesian_velocity_bicep0": "robot_arm_bicep_vel_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_bicep1": "robot_arm_bicep_vel_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_bicep2": "robot_arm_bicep_vel_z"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_velocity_end_effector0": "robot_arm_end_effector_vel_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_end_effector1": "robot_arm_end_effector_vel_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_end_effector2": "robot_arm_end_effector_vel_z"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_velocity_forearm0": "robot_arm_forearm_vel_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_forearm1": "robot_arm_forearm_vel_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_forearm2": "robot_arm_forearm_vel_z"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_velocity_shoulder0": "robot_arm_shoulder_vel_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_shoulder1": "robot_arm_shoulder_vel_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_shoulder2": "robot_arm_shoulder_vel_z"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_velocity_spherical_wrist_10": "robot_arm_spherical_wrist_1_vel_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_spherical_wrist_11": "robot_arm_spherical_wrist_1_vel_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_spherical_wrist_12": "robot_arm_spherical_wrist_1_vel_z"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_velocity_spherical_wrist_20": "robot_arm_spherical_wrist_2_vel_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_spherical_wrist_21": "robot_arm_spherical_wrist_2_vel_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_spherical_wrist_22": "robot_arm_spherical_wrist_2_vel_z"}, inplace=True)

df_s.rename(columns={"processed_data_cartesian_velocity_wheelchair0": "wheelchair_vel_x"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_wheelchair1": "wheelchair_vel_y"}, inplace=True)
df_s.rename(columns={"processed_data_cartesian_velocity_wheelchair2": "wheelchair_vel_z"}, inplace=True)

# imu
df_s.rename(columns={"processed_data_imu_angular_velocity0": "imu_gyro_x"}, inplace=True)
df_s.rename(columns={"processed_data_imu_angular_velocity1": "imu_gyro_y"}, inplace=True)
df_s.rename(columns={"processed_data_imu_angular_velocity2": "imu_gyro_z"}, inplace=True)

df_s.rename(columns={"processed_data_imu_linear_acceleration0": "imu_accel_x"}, inplace=True)
df_s.rename(columns={"processed_data_imu_linear_acceleration1": "imu_accel_y"}, inplace=True)
df_s.rename(columns={"processed_data_imu_linear_acceleration2": "imu_accel_z"}, inplace=True)

df_s.rename(columns={"processed_data_imu_orientation0": "imu_quat_x"}, inplace=True)
df_s.rename(columns={"processed_data_imu_orientation1": "imu_quat_y"}, inplace=True)
df_s.rename(columns={"processed_data_imu_orientation2": "imu_quat_z"}, inplace=True)
df_s.rename(columns={"processed_data_imu_orientation3": "imu_quat_w"}, inplace=True)

# joint states
df_s.rename(columns={"processed_data_joint_state_back_left_wheel_joint0": "back_left_wheel_joint_pos"}, inplace=True)
df_s.rename(columns={"processed_data_joint_state_back_left_wheel_joint1": "back_left_wheel_joint_vel"}, inplace=True)

df_s.rename(columns={
    "processed_data_joint_state_back_right_wheel_joint0": "back_right_wheel_joint_pos",
    "processed_data_joint_state_back_right_wheel_joint1": "back_right_wheel_joint_vel",

    "processed_data_joint_state_front_left_wheel_joint0": "front_left_wheel_joint_pos",
    "processed_data_joint_state_front_left_wheel_joint1": "front_left_wheel_joint_vel",

    "processed_data_joint_state_front_right_wheel_joint0": "front_right_wheel_joint_pos",
    "processed_data_joint_state_front_right_wheel_joint1": "front_right_wheel_joint_vel",

    "processed_data_joint_state_joint_10": "joint_1_pos",
    "processed_data_joint_state_joint_11": "joint_1_vel",

    "processed_data_joint_state_joint_20": "joint_2_pos",
    "processed_data_joint_state_joint_21": "joint_2_vel",

    "processed_data_joint_state_joint_30": "joint_3_pos",
    "processed_data_joint_state_joint_31": "joint_3_vel",

    "processed_data_joint_state_joint_40": "joint_4_pos",
    "processed_data_joint_state_joint_41": "joint_4_vel",

    "processed_data_joint_state_joint_50": "joint_5_pos",
    "processed_data_joint_state_joint_51": "joint_5_vel",

    "processed_data_joint_state_joint_60": "joint_6_pos",
    "processed_data_joint_state_joint_61": "joint_6_vel",

    "processed_data_joint_state_left_inner_knuckle_finger_tip_joint0": "left_inner_knuckle_finger_tip_joint_pos",
    "processed_data_joint_state_left_inner_knuckle_finger_tip_joint1": "left_inner_knuckle_finger_tip_joint_vel",

    "processed_data_joint_state_right_inner_knuckle_finger_tip_joint0": "right_inner_knuckle_finger_tip_joint_pos",
    "processed_data_joint_state_right_inner_knuckle_finger_tip_joint1": "right_inner_knuckle_finger_tip_joint_vel",

    "processed_data_joint_state_robotiq_85_left_finger_tip_joint0": "robotiq_85_left_finger_tip_joint_pos",
    "processed_data_joint_state_robotiq_85_left_finger_tip_joint1": "robotiq_85_left_finger_tip_joint_vel",

    "processed_data_joint_state_robotiq_85_left_knuckle_joint0": "robotiq_85_left_knuckle_joint_pos",
    "processed_data_joint_state_robotiq_85_left_knuckle_joint1": "robotiq_85_left_knuckle_joint_vel",

    "processed_data_joint_state_robotiq_85_right_finger_tip_joint0": "robotiq_85_right_finger_tip_joint_pos",
    "processed_data_joint_state_robotiq_85_right_finger_tip_joint1": "robotiq_85_right_finger_tip_joint_vel",

    "processed_data_joint_state_robotiq_85_right_knuckle_joint0": "robotiq_85_right_knuckle_joint_pos",
    "processed_data_joint_state_robotiq_85_right_knuckle_joint1": "robotiq_85_right_knuckle_joint_vel"
}, inplace=True)

"""## Add other necessary data"""

csv_path = f'/content/drive/MyDrive/data/organization/picking/pick_mustard/Experiment{n}/data_cleaned.csv'
df_cleaned = pd.read_csv(csv_path)
# df_cleaned['instructions']
df_s['instructions'] = df_cleaned['instructions'].astype("string")
df_s.columns.to_list()
df_s['trial_id'] = n
df_s['image_frame_id'] = range(1, len(df_s)+1)
# print(df_s['sim_time'])
df_s['sim_time'] = df_s['sim_time']-df_s['sim_time'][0]

# # print(df_s['sim_time'])
# out_csv_path = f'/content/drive/MyDrive/data/organization/picking/pick_mustard_test_data/Experiment{n}/final_data.csv'
# df_s.to_csv(out_csv_path, index=False)
# print(df_s['instructions'].dtype)

"""Recalculate the cartesian velocity"""

cp_header = ['robot_arm_bicep_pos_x',
'robot_arm_bicep_pos_y',
'robot_arm_bicep_pos_z',
'robot_arm_end_effector_pos_x',
'robot_arm_end_effector_pos_y',
'robot_arm_end_effector_pos_z',
'robot_arm_forearm_pos_x',
'robot_arm_forearm_pos_y',
'robot_arm_forearm_pos_z',
'robot_arm_shoulder_pos_x',
'robot_arm_shoulder_pos_y',
'robot_arm_shoulder_pos_z',
'robot_arm_spherical_wrist_1_pos_x',
'robot_arm_spherical_wrist_1_pos_y',
'robot_arm_spherical_wrist_1_pos_z',
'robot_arm_spherical_wrist_2_pos_x',
'robot_arm_spherical_wrist_2_pos_y',
'robot_arm_spherical_wrist_2_pos_z',
'wheelchair_pos_x',
'wheelchair_pos_y',
'wheelchair_pos_z'
]
cv_header = ['robot_arm_bicep_vel_x',
'robot_arm_bicep_vel_y',
'robot_arm_bicep_vel_z',
'robot_arm_end_effector_vel_x',
'robot_arm_end_effector_vel_y',
'robot_arm_end_effector_vel_z',
'robot_arm_forearm_vel_x',
'robot_arm_forearm_vel_y',
'robot_arm_forearm_vel_z',
'robot_arm_shoulder_vel_x',
'robot_arm_shoulder_vel_y',
'robot_arm_shoulder_vel_z',
'robot_arm_spherical_wrist_1_vel_x',
'robot_arm_spherical_wrist_1_vel_y',
'robot_arm_spherical_wrist_1_vel_z',
'robot_arm_spherical_wrist_2_vel_x',
'robot_arm_spherical_wrist_2_vel_y',
'robot_arm_spherical_wrist_2_vel_z',
'wheelchair_vel_x',
'wheelchair_vel_y',
'wheelchair_vel_z',
]


# Initialize velocity columns with zeros
for vel_col in cv_header:
    df_s[vel_col] = 0

# Compute velocity using finite difference method
for pos_col, vel_col in zip(cp_header, cv_header):
    df_s[vel_col] = df_s[pos_col].diff() / df_s["sim_time"].diff()

# Set the first row of velocity columns to zero explicitly
df_s[cv_header] = df_s[cv_header].fillna(0.0)

print(df_s['wheelchair_vel_x'])

"""## Label
the standard of labeling the state is:
1. if wheelchair_vel_x/y is decreasing to zero -> the end of wheelchair_navigating
2. if robotiq_85_left/right_kunckle_joint_pos increases -> gripper_grasping
3. arm_reaching is between wheelchair_navigating and gripper_grasping
4. arm retracinting is after graspper_graspping

wheelchair_navigating, arm_reaching, gripper_grasping and arm_retracting are 0, 1, 2, 3
"""

label1 = 0
label2 = 1
label3 = 2
label4 = 3

num_l1 = 57
num_l2 = 91
num_l3 = 22
num_l4 = 79
df_s['state_labels'] = (
    [label1] * num_l1 +
    [label2] * num_l2 +
    [label3] * num_l3 +
    [label4] * num_l4
)
out_csv_path = f'/content/drive/MyDrive/data/organization/picking/pick_mustard/Experiment{n}/final_data.csv'
df_s.to_csv(out_csv_path, index=False)
